# Generated by Django 4.0.4 on 2022-08-06 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_types',
            field=models.CharField(choices=[('Product', 'Product'), ('Products', 'Products'), ('ProductREVIEWS', 'ProductREVIEWS')], max_length=20),
        ),
    ]
