# Generated by Django 4.0.4 on 2022-06-02 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_img', models.ImageField(null=True, upload_to='0_home_banner')),
                ('banner_created_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
