# Generated by Django 3.2.3 on 2022-06-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catrgory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(blank=True, max_length=250, null=True)),
                ('product_desc', models.TextField(blank=True, max_length=250, null=True)),
                ('product_price', models.CharField(blank=True, max_length=20, null=True)),
                ('offer_price', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
