# Generated by Django 3.2.3 on 2022-06-03 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_app', '0004_rename_catrgory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categoty_related_name', to='Ecommerce_app.category'),
        ),
    ]
