# Generated by Django 3.2.3 on 2022-06-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_app', '0005_products_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='offer_price',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_price',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
    ]
