# Generated by Django 3.2.3 on 2022-06-03 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_app', '0006_auto_20220604_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='offer_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
