# Generated by Django 4.0.4 on 2022-06-10 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_app', '0009_products_available_color_products_product_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Available_color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='products',
            name='available_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='available_color_related_name', to='Ecommerce_app.available_color'),
        ),
    ]
