# Generated by Django 4.0.4 on 2022-06-11 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_app', '0010_available_color_alter_products_available_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
