# Generated by Django 4.0.4 on 2022-07-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_app', '0014_remove_products_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='moreINFO',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
