# Generated by Django 4.0.4 on 2022-07-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_app', '0021_alter_productreviews_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreviews',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
