# Generated by Django 4.0.4 on 2022-07-13 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_app', '0023_productreviews_createddatae'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productreviews',
            old_name='createdDatae',
            new_name='createdDate',
        ),
    ]
