# Generated by Django 4.0.4 on 2022-07-13 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_app', '0024_rename_createddatae_productreviews_createddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreviews',
            name='createdDate',
            field=models.DateField(auto_now=True),
        ),
    ]
