# Generated by Django 4.0.4 on 2022-07-13 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Ecommerce_app', '0027_alter_productreviews_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreviews',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='userREVIEW', to=settings.AUTH_USER_MODEL),
        ),
    ]
