# Generated by Django 4.0.4 on 2022-07-14 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_app', '0029_alter_productreviews_user'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productreviews',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='review_once'),
        ),
    ]
