# Generated by Django 4.0.4 on 2022-07-29 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Ecommerce_app', '0030_productreviews_review_once'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOreder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductTitle', models.CharField(blank=True, max_length=250, null=True)),
                ('Price', models.IntegerField()),
                ('Quantity', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.IntegerField()),
                ('ThanaPostCode', models.CharField(blank=True, max_length=250, null=True)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProductOrderRelatedName', to='Ecommerce_app.products')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserOrderRelatedName', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
