# Generated by Django 4.0.4 on 2022-07-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_app', '0031_productoreder'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoreder',
            name='FullAddress',
            field=models.TextField(blank=True, null=True),
        ),
    ]
