# Generated by Django 4.0.4 on 2022-07-29 12:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Ecommerce_app', '0032_productoreder_fulladdress'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductOreder',
            new_name='ProductOrder',
        ),
    ]
