# Generated by Django 4.0.4 on 2022-07-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_app', '0033_rename_productoreder_productorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='CustomerName',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
