# Generated by Django 4.0.4 on 2022-07-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_app', '0035_alter_productorder_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='Shipping',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='productorder',
            name='TotalPrice',
            field=models.IntegerField(null=True),
        ),
    ]
