# Generated by Django 4.0.4 on 2022-08-07 22:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Ecommerce_app', '0039_productorder_orderstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorder',
            name='OrderStatus',
            field=models.CharField(blank=True, choices=[('Processing', 'Processing'), ('Shipped', 'Shipped'), ('On the way', 'On the way'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled')], max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='ShopingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ShoppingCartRelatedName', to='Ecommerce_app.products')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserShoppingCartRelatedName', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
