# Generated by Django 4.0.4 on 2022-08-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_app', '0040_alter_productorder_orderstatus_shopingcart'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productreviews',
            name='review_once',
        ),
        migrations.AddConstraint(
            model_name='productreviews',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='add_to_cart_once'),
        ),
        migrations.AddConstraint(
            model_name='shopingcart',
            constraint=models.UniqueConstraint(fields=('User', 'Product'), name='review_once'),
        ),
    ]
