# Generated by Django 3.2.3 on 2022-06-24 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0011_alter_user_first_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='account_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
