# Generated by Django 4.0.4 on 2022-06-24 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0015_rename_account_user_seller_mode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='seller_mode',
            new_name='account_type',
        ),
    ]
