# Generated by Django 4.0.4 on 2022-08-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0021_alter_address_area_alter_address_home_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
